version: '3'
services:
  api:
    image: node:14.15.5
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=quizard
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"