services:
  api:
    container_name: test_api
    environment: 
      - PGUSER=quizard
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=quizDB
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quizDB
      - POSTGRES_PASSWORD=pass
volumes:
  test_db:
networks: 
  default:
    name: demo_app_test
